# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(640, 410, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 721, 111))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label.setObjectName("label")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_2.setGeometry(QtCore.QRect(310, 60, 110, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(130, 60, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(130, 20, 481, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(270, 60, 21, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(620, 20, 81, 21))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 361, 261))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 70, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.listView = QtWidgets.QListView(self.groupBox_2)
        self.listView.setGeometry(QtCore.QRect(15, 40, 241, 192))
        self.listView.setObjectName("listView")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 40, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(400, 140, 331, 261))
        self.groupBox_3.setObjectName("groupBox_3")
        self.listView_3 = QtWidgets.QListView(self.groupBox_3)
        self.listView_3.setGeometry(QtCore.QRect(160, 40, 151, 192))
        self.listView_3.setObjectName("listView_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(160, 10, 101, 31))
        self.label_6.setObjectName("label_6")
        self.listView_2 = QtWidgets.QListView(self.groupBox_3)
        self.listView_2.setGeometry(QtCore.QRect(20, 40, 111, 192))
        self.listView_2.setObjectName("listView_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 81, 31))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuCompanyDB = QtWidgets.QMenu(self.menubar)
        self.menuCompanyDB.setObjectName("menuCompanyDB")
        self.menuDataInspection = QtWidgets.QMenu(self.menubar)
        self.menuDataInspection.setTearOffEnabled(False)
        self.menuDataInspection.setObjectName("menuDataInspection")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAaa = QtWidgets.QAction(MainWindow)
        self.actionAaa.setObjectName("actionAaa")
        self.actionPersonal = QtWidgets.QAction(MainWindow)
        self.actionPersonal.setObjectName("actionPersonal")
        self.actionCompany = QtWidgets.QAction(MainWindow)
        self.actionCompany.setObjectName("actionCompany")
        self.actionStra = QtWidgets.QAction(MainWindow)
        self.actionStra.setObjectName("actionStra")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuFile.addAction(self.actionExit_2)
        self.menuSettings.addAction(self.actionStra)
        self.menuCompanyDB.addAction(self.actionPersonal)
        self.menuCompanyDB.addAction(self.actionCompany)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuCompanyDB.menuAction())
        self.menubar.addAction(self.menuDataInspection.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "mainwindow"))
        self.pushButton_4.setText(_translate("MainWindow", "보고서 작성"))
        self.label.setText(_translate("MainWindow", "DTG 폴더경로"))
        self.label_2.setText(_translate("MainWindow", "분석기간"))
        self.label_3.setText(_translate("MainWindow", "~"))
        self.pushButton.setText(_translate("MainWindow", "경로선택"))
        self.groupBox_2.setTitle(_translate("MainWindow", "필터"))
        self.pushButton_3.setText(_translate("MainWindow", "삭제"))
        self.pushButton_2.setText(_translate("MainWindow", "추가"))
        self.groupBox_3.setTitle(_translate("MainWindow", "보고서 출력"))
        self.label_6.setText(_translate("MainWindow", "출력형식"))
        self.label_5.setText(_translate("MainWindow", "출력목록"))
        self.menuFile.setTitle(_translate("MainWindow", "파일"))
        self.menuSettings.setTitle(_translate("MainWindow", "설정"))
        self.menuCompanyDB.setTitle(_translate("MainWindow", "택시DB"))
        self.menuDataInspection.setTitle(_translate("MainWindow", "데이터검증"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAaa.setText(_translate("MainWindow", "aaa"))
        self.actionPersonal.setText(_translate("MainWindow", "법인"))
        self.actionCompany.setText(_translate("MainWindow", "개인"))
        self.actionStra.setText(_translate("MainWindow", "이상치정의"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))

